server:
  port: 8810
#因为当前eureka单机，所以我们要做一些配置--注册中心2
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://user:123@localhost:8800/eureka/
     # defaultZone: http://localhost:${server.port}/eureka/

  instance:
    prefer-ip-address: true #在EUREKA中显示IP
# 设置安全账号密码,就可以重新配置defaultZone，curl风格
#如果想要去掉，则在启动类上面添加
#
#@EnableAutoConfiguration(exclude = {
#		org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration.class
#})
spring:
  security:
    user:
      name: user
      password: 123
  application:
    name: eureka1