server:
    port: 8504

spring:
    application:
        name: consulmember
#consul注册中心地址
    cloud:
        consul:
            port: 8500
            host: localhost
            discovery:
                hostname: 127.0.0.1

