server:
    port: 8504

spring:
    application:
        name: consulmember
#consul注册中心地址
    cloud:
        consul:
            port: 8500
            host: localhost
            discovery:
                hostname: 127.0.0.1

#重试机制
#default为全局配置，如果要单独配置每个服务，改为服务名
#默认为10s
feign:
    client:
        config:
            default:
                connectTimeout: 3000
                readTimeout: 3000  #默认为60s

    hystrix:
        enabled: true #开启

##hystrix 熔断器，禁止服务超时时间
#hystrix:command:default:execution:timeout:enable:false

name: ymldefault
swagger:
    base-package: com.example.consul1.controller #配置扫描包