server:
  port: 8802

spring:
  application:
     name: euclient
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8800/eureka/
      # 注册地址

user:
  url: http://user:123@localhost:8800/eureka/