server:
  port: 8505

spring:
  application:
    name: consul2
  #consul注册中心地址
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        hostname: 127.0.0.1
        #配置中心服务器
