server:
  port: 8801
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8800/eureka/
  instance:
    prefer-ip-address: true #在EUREKA中显示IP
spring:
  application:
    name: euserver #别名
