spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #healthCheckPath: ${management.contextPath}/health
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: properties
        enabled: true
      enabled: true
  application:
    name: properties
  zipkin:  #链路追踪
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
server:
  port: 8510